#!/bin/sh

printf "\nSupported modules:\n\n"

# Arch support
printf \
"         arch/mem support:\tOK\n"
printf \
"        arch/spec support:\tOK\n"

# Auth support
echo
printf \
"      auth/shadow support:\t"

if [ -e .lcrypt ]; then
	echo "OK"
else
	echo "Unsupported"
fi

# Crypt support
echo

printf \
"        crypt/aes support:\tOK\n"
printf \
"   crypt/blowfish support:\tOK\n"
printf \
"     crypt/chacha support:\tOK\n"
printf \
"        crypt/otp support:\tOK\n"
printf \
"      crypt/salsa support:\tOK\n"

# Decode support
echo

printf \
"    decode/base16 support:\tOK\n"
printf \
"    decode/base64 support:\tOK\n"

# Encode support
echo

printf \
"    encode/base16 support:\tOK\n"
printf \
"    encode/base64 support:\tOK\n"

# Generate support
echo

printf \
"  generate/random support:\tOK\n"

# Hash support
echo

printf \
"       hash/blake support:\tOK\n"
printf \
"      hash/blake2 support:\tOK\n"
printf \
"        hash/gost support:\tOK\n"
printf \
"      hash/haval* support:\tOK\n"
printf \
"         hash/md2 support:\tOK\n"
printf \
"         hash/md4 support:\tOK\n"
printf \
"         hash/md5 support:\tOK\n"
printf \
"     hash/ripemd* support:\tOK\n"
printf \
"        hash/sha* support:\tOK\n"
printf \
"      hash/tiger* support:\tOK\n"
printf \
"   hash/whirlpool support:\tOK\n"

# KDF support
echo

printf \
"       kdf/bcrypt support:\tOK\n"
printf \
"         kdf/hkdf support:\tOK\n"
printf \
"       kdf/pbkdf1 support:\tOK\n"
printf \
"       kdf/pbkdf2 support:\tOK\n"
printf \
"       kdf/scrypt support:\tOK\n"

# KE support
echo

printf \
"        ke/chreke support:\tOK\n"
printf \
"            ke/dh support:\t"

if [ -e .lgmp ]; then
	echo "OK"
else
	echo "Unsupported"
fi

printf \
"         ke/dheke support:\t"

if [ -e .lgmp ]; then
	echo "OK"
else
	echo "Unsupported"
fi

printf \
"          ke/ecdh support:\tOK\n"

# MAC support
echo

printf \
"         mac/hmac support:\tOK\n"
printf \
"     mac/poly1305 support:\tOK\n"


# TC support
echo

printf \
"           tc/mem support:\tOK\n"

## DONE ##
echo

