#!/bin/bash

if ! [ -e ".done" ]; then
	echo "Run 'do' first"
	exit 1
fi

if [ `id -u` -ne 0 ]; then
	echo "Current user is not root"
	exit 1
fi

mkdir -p /usr/lib

if [ $? -ne 0 ]; then
	echo "Failed to create /usr/lib"
	exit 1
fi

mkdir -p /usr/include/psec/

if [ $? -ne 0 ]; then
	echo "Failed to create /usr/include/psec"
	exit 1
fi

cp src/libpsec.so /usr/lib/

if [ $? -ne 0 ]; then
	echo "Failed to copy src/libpsec.so to /usr/lib"
	exit 1;
fi

cp -r include/* /usr/include/psec/

if [ $? -ne 0 ]; then
	echo "Failed to copy include/* to /usr/include/psec"
	exit 1;
fi

ldconfig

if [ $? -ne 0 ]; then
	echo "Failed to execute ldconfig"
	exit 1;
fi

echo "Installation complete."

exit 0

